name: steps examples

on:
  push

jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Show Node Version
        run: node --version

  hello_world_job:
    runs-on: ubuntu-latest
    name: Custom Action Example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Custom Action
        id: step-caller
        uses: ./.github/actions/hello
        with:
          the-caller: 'Myself'
      - name: Display Random Number
        run: echo "Random Number: ${{ steps.step-caller.outputs.random-number }}"
        shell: bash
